title:            Tony Tang
description:      Tony Tang's Academic Website
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://hcitang.github.io

# Owner/author information
owner:
  name:           Tony Tang
  avatar:         tony.jpg
  bio:            I'm an Associate Professor in Computer Science at the University of Calgary. I'm passionate about Human-Computer Interaction and other weird things.
  email:          tonyt@ucalgary.ca
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: proclubboy
  google_scholar: RG1EQowAAAAJ
  github: hcitang
# Analytics and webmaster tools stuff goes here
  google_analytics: UA-19657956-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: "/"
  - title: CV
    url: "/cv/"
  - title: Research
    url: "http://ricelab.cpsc.ucalgary.ca"
    external: true
  - title: Teaching
    url: "/teaching/"
  - title: Blog
    url: "http://ricelab.cpsc.ucalgary.ca/blog/"
    external: true
  - title: Resources
    url: /resources/
  - title: Fun
    url: /fun/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Edmonton
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: ["_pages"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]
